version: '3.7'
services:
  7days:
    image: ubuntu/7days
    volumes:
      - "/net/7days/:/root/.local/share/7DaysToDie"
    ports: 
      - "8081:8081/tcp"
      - "26900:26900/tcp"
      - "26900:26900/udp"
      - "26901:26901/udp"
      - "26902:26902/udp"
